### ISSUE TITLE
[Feature Request] Sexy comments with double star (/** */)

### ISSUE THREAD

**Issue by dylan-chong** [preservim/nerdcommenter#483] opened 2021-12-16 22:56 UTC
would be nice if there's an option to make sexy comments have a doc comment syntax (option?  separate command?)

**Comment by alerque** [comment] 2021-12-18 13:07
This appears to be a duplicate of #318. If having a separate option for this is a real need we'd be happy to consider contributions that address this.

**Closed by alerque** 2021-12-18 13:07 UTC
Labels: duplicate
