### ISSUE TITLE
[Question] Are "interfaces" not available anymore?

### ISSUE THREAD

**Issue by Penaz91** [preservim/nerdcommenter#472] opened 2021-07-29 12:10 UTC
Hello, thank you for preserving this great plugin.

I've been using it for quite some time and I based some functions on its "interfaces" (`:h NERDCommenterInterfaces`), mostly to be able to add a default "commented sexily" header to my code.

It seems those interfaces are not callable anymore (via `:call`), is it a conscious decision?

I'm not a VimScript wizard, so I wouldn't know a way around this, if it was a conscious decision.

Thank you for your attention.

**Comment by alerque** [comment] 2021-07-29 12:16
No, no functionality has been removed on purpose. This is probably an unintended issue (bug) with #376 which moved some of the code to VIM's autoload system. This is also a duplicate of #471, so I'm going to close it and please comment there / subscribe to that issue for updates. Thanks for your understanding while we sort this out.

**Closed by alerque** 2021-07-29 12:16 UTC
