### ISSUE TITLE
Support for Vue

### ISSUE THREAD

**Issue by AdamBD** [preservim/nerdcommenter#428] opened 2020-06-08 16:24 UTC
First off amazing plugin!

I wanted to see if there could be an update for Vue.js support.

Vue has single-file-components for the front end, which have a mix of CSS, JS and HTML in the same file. 

NerdCommentor seemingly recognizes only the HTML and thus will only apply HTML comments. It would be great if it would detect where in the file or what kind of code there is in the highlighted lines and apply the correct comment style either:
 - HTML
// - JS
# - CSS

**Comment by alerque** [comment] 2020-06-08 19:00
Yes, it would be lovely wouldn't it?

Unfortunately the way things stand right now only the currently set `filetype` (which in VIM is set per buffer) is used by this plugin. You can temporarily change the filetype depending on where you are, but that's a pain.

It would be possible to detect zones based on imported syntax highlighting and embed a different comment rule for those, but to date nobody has stepped up to actually implement this. There are some other commenting plugins that do, but they have different drawbacks.

We'd love to see this happen, but somebody has to actually make it work. This issue is a duplicate of #17.

**Closed by alerque** 2020-06-08 19:00 UTC
