### ISSUE TITLE
Licence change request

### ISSUE THREAD

**Issue by jonasstein** [preservim/nerdcommenter#217] opened 2015-11-22 01:30 UTC
Hi,
I respect, that the author has the right to select his favourite license but this license:
https://github.com/scrooloose/nerdcommenter/blob/master/plugin/NERD_commenter.vim#L7
makes a distribution complicate. Public domain is complicate in general [1], but especially this version:
It requires a rename of the project. 
It would be very helpful for all Linux distributions and users, if you would select one of the suggested open source licenses[2]
Found out about the problem due to a bug report on gentoo.
Best,
JS

[1] http://opensource.org/faq#public-domain
[2] http://opensource.org/licenses/alphabetical
[3] https://bugs.gentoo.org/show_bug.cgi?id=566430

**Comment by scrooloose** [comment] 2015-11-23 14:28
I dont understand the problem. Why are you required to rename the project? If you edit the license then you must rename the license. Nothing is said about having to rename the project at any point.

The license explicitly says:

```
   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION

  0. You just DO WHAT THE FUCK YOU WANT TO.
```

I dont see how this can be a problem for anyone.

**Comment by chadfurman** [comment] 2016-01-14 11:47
http://www.wtfpl.net/about/

**Comment by alerque** [comment] 2016-05-24 07:58
I agree that this is not an ideal license. I've recently been added as a maintainer to this project and there is was some talk of moving this project under a separate umbrella. That being said I don't feel free to just up and change the license on the parent project.  Perhaps this is a discussion we can have in a while after some dust settles and I get through the backlog of issues.

**Comment by chadfurman** [comment] 2016-09-05 20:58
@alerque could you tell me what is wrong with the license?  Is it the swear word?  Because, ultimately, the license lets you... well... do anything.  As long as you change the name?

**Comment by alerque** [comment] 2016-09-06 05:58
@chadfurman The swear word sure doesn't help, but that's not the main issue. The issue is that the license does _NOT_ ultimately allow you  do do anything. Public domain style licensing is not a magic wand that makes it usable by everybody, especially if you're not in the West. Many countries flat out  reject non-explicit licenses and restrict the distribution of such material. Partly due to this, some software (including Linux) distributions won't package such software.

Beyond the outright  legal issues there are also ideological ones. Some disctros only package and distribute things that have explicit permissions, and some limit themselves to specifically FOSS compatible  licenses.

Personally I'm a fan of share-alike licenses and would have used some variant of the GPL if this was my own project (probably LGPL to make bundling with vim easier). But I'm also not going to try to argue for that here.

I would actually suggest the MIT license as likely the best choice given where this project is coming from.

**Comment by alerque** [comment] 2019-12-30 09:18
Now that this project has moved under the @preservim namespace and I'm marked as one of the owners, I would like to deal with this issue. Given that the WTFPL has been legally shown to _allow_ re-licensing, I think we can do this without causing problems. If we were to pick a more restrictive license (say one that required attribution) it would only apply to contributions after the license was applied, anybody could still fork from before that point under the original terms.

Some issues I see with the current license.

1. Call me a prude, but the license name itself is not something I want to read out-loud to my kids.

1. The legality in some jurisdictions is suspect. Many distros have decided it's okay and most people won't care about this, but technically it makes it illegal to use in some countries.

1. It doesn't provide any protection from liability. Technically this is somewhat mitigated by the extra clauses on the license notice that aren't part of the license, but it would be better if the license dealt with the issue of liability.

As a matter of personal preference I strongly support share-alike licensing, but given the long history of this project under permissive licensing I won't try to impose that on current or future contributors.

**In the spirit of legally compatibility with the existing license**, I see these options:

* MIT — recognizable, legally proven, easy to distribute, only adds requirement that license notice remain, includes limitation of liability and warranty.
* CC0 — much more verbose (yuck) but very much in the same spirit, a robust legal disavowment of  rights that is much easier to make stick in any legal situation, also includes more limitation of liability than MIT, only not released restriction is on using the name or content in a trademark/patent situation. 
* Unlicense ­— closes successor of WTFPL without the objectionable name and with  some of the extra legal problems of liability dealt with. Only partially solves issue 2.

**Comment by wsdjeg** [comment] 2020-01-23 10:34
please stop move popular plugins to your own org Group and change the license. the license should be keep same as before.

**Comment by wsdjeg** [comment] 2020-01-23 10:37
@scrooloose We use these plugins more because we trust you, and if you give it to someone else, you need to alert the user.

**Comment by scrooloose** [comment] 2020-01-23 10:58
@wsdjeg I appreciate that the change in ownership is sudden and jarring. However, @alerque has been doing all the work for several years now with almost no oversight from me.

So I think you can trust him.

His tastes are different to mine (I like swear words - they are funny to me), but I trust him to make sensible decisions. His history with the project is solid.

**Comment by wsdjeg** [comment] 2020-01-23 11:29
> So I think you can trust him.

:) ok ,thanks for your reply.

**Comment by alerque** [comment] 2020-01-23 22:03
@wsdjeg If you have any specific concerns about the way I'm managing this project please do feel free to speak up. That being said the change was announced pretty loudly in issue comments back in 2016. The repository migration wasn't announced as loudly because it was pretty much a no-op from a project management standpoint.

That's changed a little and will change more in the future as more people join the @preservim project. There are a couple of other folks with access to this repository now, but they are all people wil long track records with vim plugins and your probably already trust their code anyway.

Also, I would note that for open source projects the trust involved really isn't dependent so much on individuals since you can review the code. For example you can look up every change I've made to this project in the last 4 years and you don't have to wonder what I may or may not have done to it.

In relation to this issue:

> the license should be keep same as before.

Can you explain _why_ you feel this way? What would the proposed licensees restrict you from doing that you are able to do now? All of the proposals are for permissive licensees that cover pretty much the same ground, and the pros and conns of switching are noted above. If you have some point that I've overlooked that would be a drawback to the proposal I'd be glad to consider it, but there needs to be a reason.

**Closed** 2020-06-08 11:25 UTC
Labels: question

**Comment by wsdjeg** [comment] 2020-06-08 11:30
Why the author info is removed?
--------------
wsdjeg

**Comment by alerque** [comment] 2020-06-08 12:03
@wsdjeg, It was not removed, it was just *moved*. The Readme never used to contain any credit information, now it does. Please see the commit comments on f72adff for the logic of not having them in each file. That's a holdover from when vim plugins were one file and were passed around that way. Now they are almost universally distributed as a couple of files with a standard directory structure, and the relevant meta data has been placed in the most accessible *current* location.

**Comment by wsdjeg** [comment] 2020-06-08 12:28
So where is the origin author info? In https://github.com/preservim/nerdcommenter/pull/412 I just see you put it in changelog. but it is removed too.

**Comment by alerque** [comment] 2020-06-08 12:44
@wsdjeg I don't know what you are refering to now, please be specific. I could be wrong (and I'd be happy to learn I was wrong) but at this point I'm starting to feel like you are just objecting to everything I do. What have I done to offend you? Why are all my contributions (here and on other projects) met with only negative comments? I know you never agred with the re-licensing issue here, but even though you are not a contributor I asked for any specific reason why the license proposal would be worse for your usage rather than better and gave you months to reply. No contributors objected, not even the original author.

I have [gone out of my way to get the original author even more visible credit](https://github.com/preservim/nerdcommenter/pull/412#issuecomment-569627926) than before, I'm really at a loss as to why you are objecting. What is worse now that it was before I started maintaining this plugin 4 years ago?

**Comment by wsdjeg** [comment] 2020-06-08 12:59
Ok. sorry, and thanks for all your work.
